all:
	gcc -Wall server31.c llist.c -o server31
	gcc -Wall server32.c llist.c -o server32
	gcc -Wall server33.c llist.c -o server33
	gcc -Wall server34.c llist.c -o server34
	gcc -Wall -g client3.c -o client3 `pkg-config --cflags gtk+-2.0 --libs gtk+-2.0`
